import { readFile, writeFile, mkdir, cp, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const source = path.resolve(root, '../flight400-demo-main');
const destination = path.join(root, 'src/content/docs');
const base = (process.env.SITE_BASE || '/').replace(/\/$/, '');
const github = 'https://github.com/pedro-moreira-ibm/bob-ppi-workshop/blob/main/flight400-demo-main';
await mkdir(destination, { recursive: true });
await mkdir(path.join(root, 'public/lab'), { recursive: true });
// Remove pages and assets generated by earlier versions of the presentation.
for (const file of [
  path.join(destination, 'reference.md'),
  path.join(destination, 'sample-skill.md'),
  path.join(root, 'public/lab/FLIGHT400-GUIDE.md'),
  path.join(root, 'public/lab/FLGHT400-architecture.drawio'),
]) await rm(file, { force: true });
await writeFile(path.join(root, 'public/preview-config.json'), JSON.stringify({ base }));
// Explicit allowlist: credentials and unrelated repository files never enter the site.
await cp(path.join(source, 'pics'), path.join(root, 'public/lab/pics'), { recursive: true });
for (const file of ['SAMPLE-SKILL.md']) {
  await cp(path.join(source, file), path.join(root, 'public/lab', file));
}
function links(text) {
  return text.replace(/(src="|\]\()(?:\.\/)?pics\//g, `$1${base}/lab/pics/`)
    .replace(/\]\(\.\/SAMPLE-SKILL\.md\)/g, `](${base}/lab/SAMPLE-SKILL.md)`)
    .replace(/\]\(ssh_private_key\.pem\)/g, `](${github}/ssh_private_key.pem)`);
}
function sharedPresentation(text) {
  return text
    .replace(/Bob chat UI/gi, 'Bob IDE')
    .replace(/Bob chat panel/gi, 'Bob IDE chat panel')
    .replace(/,? (?:and )?replacing `nn` with the two-digit suffix of your assigned library \(e\.g\. `01` for `FLGHT401`, `02` for `FLGHT402`\)/g, '')
    .replace(/\. Also replace `30nn` with your assigned development port \(e\.g\. `3001` for `FLGHT401`, `3002` for `FLGHT402`\)/g, '')
    .replace(/⚠️ Ask Bob/g, 'Ask Bob');
}
function workshopPresentation(text, slug) {
  let body = sharedPresentation(text);
  if (slug === 'setup') {
    body = body
      .replace('### 1. Install the Premium Package for i / IBM i Developer Pack for VS Code and Bob IDE', '### 1. Install the Premium Package for i')
      .replace('⚠️ The instructor will create libraries FLGHT401 through FLGHT4nn, each containing a full copy of all objects from FLGHT400. Each participant will have their assigned library (e.g. FLGHT401) added to their library list.\n\n⚠️ Throughout the labs, participants must only use **their assigned number** so everyone can enjoy the labs.\n\n| Student # | Library | Dev Port | React App URL |\n|:---------:|---------|:--------:|---------------|\n| 1  | FLGHT401 | 3001 | http://localhost:3001 |\n| 2  | FLGHT402 | 3002 | http://localhost:3002 |\n| 3  | FLGHT403 | 3003 | http://localhost:3003 |\n| 4  | FLGHT404 | 3004 | http://localhost:3004 |\n| … | … | … | … |\n| 50 | FLGHT450 | 3050 | http://localhost:3050 |', 'The instructor assigns each participant a dedicated copy of the application. Choose your participant number in **Your Workspace** above; the values below and all personalized instructions in the workshop update automatically.\n\n| Your library | Your dev port | Your React app URL |\n|:------------:|:-------------:|--------------------|\n| `FLGHT4nn` | `30nn` | `http://localhost:30nn` |')
      .replace('In the Code for IBM i object browser, browse library FLGHT4nn where you replace nn with your library number given to you by the instructor (ex: FLGHT400, FLGHT401, etc.)', 'In the Code for IBM i object browser, browse your assigned `FLGHT4nn` library');
  }
  if (slug === 'exercise-1') {
    body = body
      .replace("Add **FLGHT4nn** (⚠️replace the 'nn' with your library number) to your library list", 'Add your assigned **FLGHT4nn** library to your library list')
      .replace(/4\. Ask Bob the following[^\n]*/, '4. Ask Bob with the following personalized prompt.')
      .replace(/2\. Ask Bob using the `\/erd` slash command[^\n]*/, '2. Ask Bob using the `/erd` slash command (make sure it is highlighted in the chat).')
      .replace('4. ⚠️ At the end, specify an output location on the IFS **unique to your library number**. For example: /home/ITZUSER/flght400/docs/business-rules/FRS401-2026-07-16T19-34-14.md', '4. At the end, use this personalized IFS output location: `/home/ITZUSER/flght4nn/docs/business-rules/business-rules.md`.');
  }
  if (slug === 'exercise-2') body = body.replace('### 2.1. Understand FRS409 (order modification confirmation)', '### 2.1. Understand FRS409');
  if (slug === 'exercise-2') body = body.replace('`FRS409` is the **Order Modification Confirmation Window** — an OPM RPG program that displays a confirmation popup when a user modifies an order.', '`FRS409` is an OPM RPG program that displays a confirmation popup when a user modifies an order.');
  if (slug === 'exercise-3') {
    body = body
      .replace(/(\d+\.) Ask Bob[^\n]*replacing[^\n]*/, '$1 Ask Bob with the following personalized prompt.')
      .replace(/\s*<pre>\s*If another program such as `FRS003`, `FRS413`, or `BFLGHT` is also affected, record it as follow-up work\.\s*Do not update or compile it during the workshop or leave it as an item at the end\. <\/pre>/, '\n\n> **Note:** If another program such as `FRS003`, `FRS413`, or `BFLGHT` is also affected, record it as follow-up work. Do not update or compile it during the workshop; leave it as a follow-up item.\n')
      .replace(/<pre>\s*Bob may identify other programs that use `FLIGHTS` or `FLIGHTSZ`\.\s*Those dependencies are valuable impact-analysis findings, but they are outside the scope of the exercise\.\s*In a production change, those programs would be reviewed and recompiled separately\. <\/pre>/, '> **Note:** Bob may identify other programs that use `FLIGHTS` or `FLIGHTSZ`. These dependencies are valuable impact-analysis findings, but are outside the scope of this exercise. In a production change, review and recompile them separately.');
  }
  if (slug === 'exercise-4') {
    body = body
      .replace(/3\. Ask Bob to review the following SQL query using the comand `\/review`[^\n]*/, '3. Ask Bob to review the SQL query using the `/review` command before pasting it into Bob.')
      .replace(/^- ❌ /gm, '- **Issue:** ')
      .replace(/^- ⚠️ /gm, '- **Review:** ')
      .replace(/^- ✅ /gm, '- **Strength:** ')
      .replace(/^- 💡 /gm, '- **Suggestion:** ')
      .replace('### 4.3. Explain the performance characteristics (optional)', '### 4.2. Explain the performance characteristics')
      .replace('### 4.4. Run the Index Advisor workflow', '### 4.3. Run the Index Advisor workflow')
      .replace('- `FLGHT400` attendees create indexes only in `FLGHT400`\n- `FLGHT401` attendees create indexes only in `FLGHT401`\n- `FLGHT402` attendees create indexes only in `FLGHT402`\n- etc.', '- Create indexes only in your assigned `FLGHT4nn` schema.')
      .replace('Bob may discover similar recommendations in multiple `FLGHT4nn` schemas — this is expected because each schema contains a copy of the same application data. Do not create indexes in schemas that were not assigned to you.', 'Bob may discover similar recommendations in other schemas because each contains a copy of the same application data. Do not create indexes outside your assigned `FLGHT4nn` schema.');
  }
  if (slug === 'exercise-5') {
    body = body
      .replace('In this exercise, you will use Bob in IBM i Developer mode to answer system-level questions using two natural language prompts.\n', 'In this exercise, you will use Bob in IBM i Developer mode to answer system-level questions using natural language prompts.\n\n### 5.1. Explore your system with Bob\n')
      .replace(/4\. Ask Bob which program objects[^\n]*\n\nAsk Bob the following[^\n]*/, '4. Ask Bob which program objects were created or recreated more than five years ago using the following personalized prompt:');
  }
  if (slug === 'exercise-6') {
    body = body
      .replace('### Prerequisites — Install RPGUnit', '### 6.1. Install RPGUnit prerequisites')
      .replace('### 6.1. Create a new source member `CUSTCHK`', '### 6.2. Create a new source member `CUSTCHK`')
      .replace('### 6.2. Run the RPGUnit Test Plan Creation workflow', '### 6.3. Run the RPGUnit Test Plan Creation workflow')
      .replace('### 6.3. Run the RPGUnit Test Suite Implementation workflow', '### 6.4. Run the RPGUnit Test Suite Implementation workflow')
      .replace('used in step 6.3', 'used in step 6.4')
      .replace('since the required test plan was already created in step 6.2', 'since the required test plan was already created in step 6.3')
      .replace('2. Enter the name', '\n2. Enter the name')
      .replace('13. 💡 ', '13. ');
  }
  if (slug === 'exercise-7') {
    body = body
      .replace(/💡 /g, '')
      .replace('### Environment setup', '### 7.1. Prepare the environment')
      .replace('3. Replace `<DEV_PORT>` with the port assigned to your library. For example, `FLGHT401` uses port `3001`, `FLGHT402` uses port `3002`, and so on.', '3. The tunnel command below automatically shows the development port for your selected participant.')
      .replace('### Sharpen your skill', '### 7.2. Sharpen your skill')
      .replace('### Prompt in Bob IDE', '### 7.3. Build and explore the React app')
      .replace('### Skills & tools used behind the scenes', '#### Skills & tools used behind the scenes')
      .replace(/^### Expected result/gm, '#### Expected result')
      .replace(/2\. Ask Bob the following[^\n]*/, '2. Ask Bob with the following personalized prompt.')
      .replace(/1\. Ask Bob to stop the development server[^\n]*/, '1. Ask Bob to stop the personalized development server when you finish exploring the React app:')
      .replace('✅ **Optional exercise completed**', '✅ **Exercise 7 completed**');
  }
  if (slug === 'summary') {
    body = body
      .replace('Congratulations! In this lab you:', `<section class="summary-celebration">
<span class="eyebrow">WORKSHOP COMPLETE</span>
<span class="summary-mark" aria-hidden="true">✓</span>
<h2>Congratulations!</h2>
<p>You completed the Flight400 modernization journey with IBM Bob.</p>
</section>

## What you accomplished`)
      .replace(/\n\*\*Next steps:\*\*[^\n]*\n?/, '\n');
  }
  return body;
}
async function page(slug, title, body, extra = '') {
  await writeFile(path.join(destination, `${slug}.md`), `---\ntitle: ${JSON.stringify(title)}\n${extra}---\n\n${links(body)}`);
}
const readme = await readFile(path.join(source, 'README.md'), 'utf8');
const sections = [...readme.matchAll(/^## (.+)$/gm)];
const manifest = [];
for (let i = 0; i < sections.length; i++) {
  const heading = sections[i][1];
  const slug = heading.startsWith('Environment') ? 'setup' : heading.startsWith('Summary') ? 'summary' : `exercise-${heading.match(/Exercise (\d)/)?.[1]}`;
  if (slug.includes('undefined')) throw new Error(`Unrecognized section: ${heading}`);
  const sourceBody = readme.slice(sections[i].index + sections[i][0].length, sections[i+1]?.index ?? readme.length);
  const body = workshopPresentation(sourceBody, slug);
  const title = slug === 'exercise-7' ? 'Exercise 7 — Generate a React Carbon app from a green screen' : heading;
  await page(slug, title, body, 'tableOfContents:\n  minHeadingLevel: 3\n  maxHeadingLevel: 3\n');
  manifest.push({ slug, heading, sourceCharacters: sourceBody.length, outputCharacters: body.length });
}
const cards = [
  ['01','Understand the application','Generate architecture documentation, map database relationships, and extract business rules from legacy RPG with IBM Bob.','exercise-1','Explore'],
  ['02','Modernize RPG','Understand a fixed-format OPM RPG program, convert it to free-format ILE RPG, compile it, and review the modernization report.','exercise-2','Transform'],
  ['03','Expand a business field','Trace Total Flight Hours across DDS, RPG, and the 5250 screen, then build and validate the complete application path.','exercise-3','Build'],
  ['04','Optimize SQL','Review and correct a Db2 for i query, examine its performance characteristics, and apply an Index Advisor recommendation.','exercise-4','Optimize'],
  ['05','Explore your system','Use natural language to inspect active jobs, CPU activity, job details, and older IBM i program objects.','exercise-5','Discover'],
  ['06','Build confidence with tests','Create an RPGUnit plan, implement its test suites, run them, and use IBM Bob to investigate failures.','exercise-6','Validate'],
  ['07','Build a React interface','Create a reusable skill, modernize a 5250 screen as a React and Carbon app, and run it directly on IBM i PASE.','exercise-7','Optional exercise'],
];
await page('index', 'Modernize IBM i applications with IBM Bob', `
<div class="overview-hero">
<span class="eyebrow">IBM BOB · PREMIUM PACKAGE FOR i</span>
<p class="hero-lead">Your IBM i modernization journey starts here.</p>
<p>Get hands-on with Flight400. Understand an existing application, evolve its code, and explore what comes next—with Bob alongside you.</p>
<div class="hero-actions"><a class="primary-action" href="${base}/setup/">Begin the workshop <span>↗</span></a></div>
<div class="hero-facts"><span><strong>06</strong> core exercises</span><span><strong>01</strong> optional exercise</span></div>
</div>

## Your flight plan

Start with environment setup, then follow the exercises at your own pace or with your instructor.

<a class="setup-card" href="${base}/setup/"><span class="stage-number">00</span><span><strong>Prepare your environment</strong><br />Install the extensions, connect to IBM i, and select your assigned library.</span><span aria-hidden="true">→</span></a>

<div class="exercise-grid">
${cards.map(([n,title,description,slug,tag])=>`<a class="exercise-card" href="${base}/${slug}/"><div class="card-top"><span class="stage-number">${n}</span><span class="card-tag">${tag}</span></div><strong>${title}</strong><p>${description}</p><span class="card-link">Open exercise <span aria-hidden="true">↗</span></span></a>`).join('\n')}
</div>
`, 'tableOfContents: false\n');
await writeFile(path.join(root, '.content-manifest.json'), JSON.stringify(manifest, null, 2)+'\n');
console.log(`Generated ${manifest.length + 1} pages from original Markdown. Original files unchanged.`);
